backend:
  name: github
  branch: master # Branch to update (optional; defaults to master)
  repo: ergoplatform/sigmaverse
  base_url: https://sigmaverse.io

publish_mode: editorial_workflow
media_folder: "static" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads


collections:
  - name: 'new_project'
    label: 'Project'
    description: "All sigmaverse projects"
    folder: 'applications'
    path: '{{slug}}/overview'
    create: true
    identifier_field: name
    fields:
      - {
        label: "Name",
        name: "name",
        widget: "text"
      }
      - {
        label: "Description",
        name: "description",
        widget: "text"
      }
      - {
        label: "Website",
        name: "website",
        widget: "text"
      }
      - {
        label: "Logotype",
        name: "logo_image",
        widget: "image",
      }
      - {
        label: "Preview",
        name: "preview_image",
        widget: "image",
      }
      - {
        label: "Category",
        name: "category",
        widget: "select",
        multiple: false,
        options: ['dApps', 'Privacy', 'NFTs', 'Metaverse', 'Explore', 'Mining', 'Tooling', 'Tokens', 'Wallets', 'Dev Tools'],
      }
      - { label: 'Date', name: 'date', widget: 'datetime' }

  - name: 'new_carousel_project'
    label: 'Featured carousel'
    description: "All featured carousel projects"
    folder: 'carousel'
    path: '{{slug}}'
    media_folder: '/public/images/carousel/'
    public_folder: ''
    identifier_field: name
    fields:
      - {
        label: "Name",
        name: "name",
        widget: "text"
      }
      - {
        label: "Project Title",
        name: "title",
        widget: "text"
      }
      - {
        label: "Description",
        name: "description",
        widget: "text"
      }
      - {
        label: "Project website",
        name: "website",
        widget: "text"
      }
      - {
        label: "Logotype",
        name: "logo_image",
        widget: "image",
      }
      - {
        label: "Carousel Image",
        name: "preview_image",
        widget: "image",
      }
